{% set name = "beets" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beets-{{ version }}.tar.gz
  sha256: a0abcdf95d5f89fcf46b07ddc2b5b92e1dd5abe68f4cc7222f21aff2dffc4789

build:
  entry_points:
    - beet = beets.ui:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - unidecode >=1.3.6
    - musicbrainzngs >=0.4
    - pyyaml
    - mediafile >=0.12.0
    - confuse >=1.5.0
    - munkres >=1.0.0
    - jellyfish
    - colorama
    - typing-extensions

test:
  imports:
    - beets
    - beetsplug
  commands:
    - pip check
    - beet --help
  requires:
    - pip

about:
  home: https://beets.io/
  summary: music tagger and library organizer
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/beetbox/beets
  doc_url: https://beets.readthedocs.io/


extra:
  recipe-maintainers:
    - HeavyTony2
